command:
  - "python"
  - "app.py"

env:
  - name: LAKEBASE_SECRET_SCOPE
    value: "database-hw1"
  - name: LAKEBASE_SECRET_KEY
    value: "lakebase-ticketing-url"
  - name: TICKETS_TABLE_NAME
    value: "tickets"
  - name: MESSAGES_TABLE_NAME
    value: "ticket_messages"
